### ISSUE TITLE
Session Scaling

### ISSUE THREAD

**Issue by sgoldsmith71** [leeej84/PowerScale#1]
Hi Lee...I was trying to work out why it wasnt scaling up for me and I think you'll find this should be 
($machineScaling -eq "**Sessions**") not **Session**

Apart from that it is working brilliantly.

Steve

https://github.com/leeej84/PowerScale/blob/4b20f7c1730504ff5ff9cff5ac0ca1921f04f35a/Decision%20Making.ps1#L1219

**Comment by leeej84** [comment]
Spot on, thank you.
