### ISSUE TITLE
scale up after scale down

### ISSUE THREAD

**Issue by jvondermans** [leeej84/PowerScale#10]
Hi Lee,

I'm having trouble solving an issue, which I think could be solved. It is not occurring very often, but once or twice a week.

When the script needs to scale down, because of decreasing number of users (I use the average sessions for scaling). The script puts a machine in Maintanance to drain those users. So far so good.

If right after I need to scale up because of an increase in users, the script turns on a machine. 

What I would rather have is that the machine that is in maintanance mode, is to get out of maintanance mode. This in stead of a new machine being turned on. For this the machine with the most sessions still alive should be get out of maintanance first, etc.

Using this procedure we could save even more on Azure consumption. 

Something to think of with a new Realease, hopefully you do know how to solve this.

Jordy

**Comment by leeej84** [comment]
Thanks Jordy, awesome.

Sounds like a plan. I think I already have that logic in there actually but maybe not during the drain period.

If you log it as an issue in github I'll work on it. No worries.

Thank you.

Kind Regards

Leee Jeffries

________________________________

**Comment by leeej84** [comment]
Hi Jordy

Just to let you know I’ve not forgotten you.

I’ve just been very busy.

Kind Regards

Leee Jeffries
Managing Director
Leee Jeffries Consulting
A unique view of Virtual Computing

**Comment by jvondermans** [comment]
Hi Leee,

No problem, I'll see it whenever you have the time. The script is already saving us a lot of money. this is just tweaking it to make it better!

Regards,
Jordy

________________________________
Van: Leee Jeffries <notifications@github.com>
Verzonden: zondag 1 maart 2020 21:17
Aan: leeej84/PowerScale <PowerScale@noreply.github.com>
CC: jvondermans <jvondermans@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [leeej84/PowerScale] scale up after scale down (#10)

Hi Jordy

Just to let you know I’ve not forgotten you.

I’ve just been very busy.

Kind Regards

Leee Jeffries
Managing Director
Leee Jeffries Consulting
A unique view of Virtual Computing

**Comment by leeej84** [comment]
I'm really pleased it's helped. I saw that as a huge gap for hybrid cloud customers.

It's pretty easy to setup and get to grips with. Any improvements you think could be made?

Kind Regards

Leee Jeffries

________________________________

**Comment by jvondermans** [comment]
Hi Leee,

You're right, the gap from working with the traditional Citrix setup to the Citrix cloud is huge, especially in price 😉.

I've discussed this with a colleague and we came up with 2 enhancements:

  *   an extra timeframe where you can spin up extra machines. In the script you can set the scaling to a number of machines, which is fine during 22 hours of the day. but when a lot of people come in (between 8-10) you might want to scale a different number for quick response. In our case we set the scaling to 1 but in the morning I would like to set it to 3.
  *   an option to reboot/drain all machines over night, so all people move to other machines (with messages and time frames, lets say an half hour to log out and in again). this way when you have a new base image you can gradually roll this out, without having people to completely run out of an environment. if this is an option in weekdays and timeframe, you could setup a maintenance window. In theory it is now possible that a single machine stays on all the time because of the number of people logged in (we use session average).

If you want of need more explanation, don't worry. I'm happy to explain 🙂.

Just a curious question, do you work from the UK or US? this to know in which timezone you are

regards,
Jordy

________________________________
Van: Leee Jeffries <notifications@github.com>
Verzonden: maandag 2 maart 2020 09:03
Aan: leeej84/PowerScale <PowerScale@noreply.github.com>
CC: jvondermans <jvondermans@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [leeej84/PowerScale] scale up after scale down (#10)

I'm really pleased it's helped. I saw that as a huge gap for hybrid cloud customers.

It's pretty easy to setup and get to grips with. Any improvements you think could be made?

Kind Regards

Leee Jeffries

________________________________

**Comment by leeej84** [comment]
Hi Jordy

I'm in the UK, thanks for the suggestions. I need to give them some time to formulate how they might fit. Sounds like some cool ideas.

Technically anything is possible.

Regards

Leee

Kind Regards

Leee Jeffries

________________________________

**Comment by vivarma-1109** [comment]
Hello Lee, 

Thank you very much for the script, as it is saving a lot of us. As the part of the issue is there any resolution, like during the scaling it is powering on the new machine instead using the existing machine in Maintenance mode.

**Comment by leeej84** [comment]
Hi @vivarma-1109 

This is actually expected behaviour for scaling. It does not check if machines are in maintenance mode when scaling and remove then. It does do this when powering machines on though. I cannot guarantee a timeframe on adding this but it can be done.

Regards

Leee

**Comment by leeej84** [comment]
Hi All, 

I have changed the behaviour of machine scaling. Maintenance mode machines will now be taken out of maintenance mode if scaling is activated in favour of powering on a new machine. There is a side effect; however, machines in maintenance mode will no longer appear in the performance measurements. If they are, we cannot scale correctly.

**Comment by leeej84** [comment]
One more note, take the release and not the live branch, I'm currently checking in code for other features and wouldn't want you to have unpredicatble results.

**Comment by leeej84** [comment]
I hope this fixed your issue, do comment if it did not.
