### ISSUE TITLE
Access to slack

### ISSUE THREAD

**Issue by GithubPate** [leeej84/PowerScale#13]
HI!
If I wanted to reach out..there is a mention to slack...slack says "please contact admin"
So my q is : who and how to access?

**Comment by leeej84** [comment]
https://worldofeuc.slack.com/messages/CLCSCA8LR

Link here from the readme.

**Comment by GithubPate** [comment]
Don't have an account on this workspace yet?Contact the workspace administrator for an invitation

**Comment by leeej84** [comment]
Okay, something has changed, I will find the registration link.

Kind Regards

Leee Jeffries
Managing Director
Leee Jeffries Consulting

**Comment by leeej84** [comment]
https://worldofeuc.slack.com/join/shared_invite/zt-dexotib9-vL0IzKmh9QhPrGxE8LotAA

**Comment by leeej84** [comment]
Even better - https://worldofeuc.github.io/Website/

**Comment by GithubPate** [comment]
thx and thx for powerscale..just implementing it
