### ISSUE TITLE
LoadIndex and Session Scale Up

### ISSUE THREAD

**Issue by nczabaranek** [leeej84/PowerScale#14]
Looks like there is an issue with getting load index and session numbers during the performance measuring jobs.

Lines 934, 935 and 1017, 1018
LoadIndex = (Get-BrokerMachine -AdminAddress $controller | Where-Object {$_.DNSName -eq $computer}) | Select-Object -expand LoadIndex
Sessions = (Get-BrokerMachine -AdminAddress $controller | Where-Object {$_.DNSName -eq $computer}) | Select-Object -expand SessionCount

These seem to need -MaxRecordCount added to the Get-BrokerMachine call to ensure you pull all records. Without it we saw improper calculations for index and sessions.

**Comment by leeej84** [comment]
Thanks very much, I'll amend that.

How many machines do you have running?

**Comment by leeej84** [comment]
This has been tested and added to the main branch.

**Comment by nczabaranek** [comment]
About 450 at the moment in Azure. No other issues seen at the moment!

**Comment by leeej84** [comment]
Awesome stuff, brilliant.
