### ISSUE TITLE
Graphs - readability

### ISSUE THREAD

**Issue by JimKarlson** [leeej84/PowerScale#15]
Thanks for the work on this tool!  We are liking it.  Graph help/ideas:  

1. The data seems to be growing and growing in the graphs.  Is there an easy way to truncate the data set in a setting someplace that we are missing?  As more data points are in the same graph it's very difficult to see what's really happening with numbers.  Getting to that "one" data point is challenging.  :)
2. Or better yet, give us a way to zoom-in on a section of the graph by applying a filter on the days/hours we would like to review.

**Comment by leeej84** [comment]
Hi Jim

What do you have your dashboard retention value set to in the config? It should create you a new dashboard each day at a certain time based on the config.

Kind Regards

Leee Jeffries

________________________________

**Comment by leeej84** [comment]
How did you get on @JimKarlson ?

**Comment by JimKarlson** [comment]
Hi Leee:  The retention value is set to 7.  
   Dashboard Retention: 7
   Logfile Retention: 7

Jim

**Comment by leeej84** [comment]
Thanks Jim, please attach your logfile and I'll review whats going on here.

**Comment by JimKarlson** [comment]
> How did you get on @JimKarlson ?

Hi Leee:  I'm not sure I understand the question regarding how I got on.

**Comment by leeej84** [comment]
Jim supplied information and we were able to nail down the issue. Closing the issue.
