### ISSUE TITLE
Additional Scaling when not business days

### ISSUE THREAD

**Issue by JimKarlson** [leeej84/PowerScale#19]
Create a variable that is set in the Create Config File.ps1.  The variable is Yes/No for running additional scaling based on business days. 

$AdditionalScaleNonBusDay =  Yes/No

Then a small bit of code to implement.  (Small may be relative ... :)  )

**Comment by leeej84** [comment]
Hi Jim, Apologies for the late response on this. So, behaviour right now is to scale outside of business hours. I am assuming you dont want to scale outside of business hours?

**Comment by leeej84** [comment]
Hi Jim, toggle added. If its a holiday, a non defined business day or out of hours this switch will allow scaling to be disabled:
scaleOutsideOfHours

Let me know.

**Comment by leeej84** [comment]
Confirmed as working, closing the issue.
