### ISSUE TITLE
Add ability to list holidays

### ISSUE THREAD

**Issue by JimKarlson** [leeej84/PowerScale#20]
Adding the ability for admins to list holidays by date;  this would allow the system to be setup to treat the identified holidays like non-business days.  Thereby reducing mistakes when an admin forgets to update the config just prior to the holiday.  In larger systems, this kind of an error can be thousands of dollars/pounds.

**Comment by leeej84** [comment]
Also added in the current branch, a new parameter has been added:
holidayDays

These should match your locale as the matching is done on the array of strings. I could fine tune it later if needed though.

**Comment by leeej84** [comment]
Confirmed as working on test runs, closing the issue.
