### ISSUE TITLE
respectDisconnected

### ISSUE THREAD

**Issue by sgoldsmith71** [leeej84/PowerScale#21]
Hi @leeej84 

I was trying to work out why it kept booting my disconnected users, even though I had respectDisconnected set to true, after some trouble shooting, I realised that Decision Making.ps1 was missing the line
$respectDisconnected = $configInfo.respectDisconnected

Hope this helps some others.

Thanks for such a brilliant tool.
Steve

**Comment by leeej84** [comment]
Hi Steve

Thank you for pointing that out. I've amended that and uploaded to the current branch already.

No problems at all. I have a webinar on Friday to spread the word.

Leee
