### ISSUE TITLE
Shutdown hosts even with adminusers logged in

### ISSUE THREAD

**Issue by saimen-ti** [leeej84/PowerScale#25]
Hi,
Our admin Users don’t have idle timeout policy set so if a adminuser doesn’t log out powerscale would not shutdown the machine. 
Would be nice to handle it with the script, maybe shutting down machine if the idle time of users exceed x hours. 
what do you think about?

**Comment by leeej84** [comment]
It is possible, why not simply apply a GPO targetted to Admin users to log them off though?

**Comment by saimen-ti** [comment]
thanks Leee, your are right! makes more sense doing it with policies

**Comment by leeej84** [comment]
No problems at all.

Kind Regards

Leee Jeffries
Managing Director
Leee Jeffries Consulting

**Comment by saimen-ti** [comment]
will be solved with gpo
