### ISSUE TITLE
Machines in maintenance mode are not shutdown and performance metrics are not calculated

### ISSUE THREAD

**Issue by leeej84** [leeej84/PowerScale#28]
Hi Leee, thanks for taking the time.

It seems the script is not taking into account the average Index but only the index of VDA02 that is Powered ON and out of maintenance mode.

If I manually take VDA03 out of maintenance mode, VDA02 AND VDA03 metrics are calculated, then the script correctly shut down VDA03:

VERBOSE: -
VERBOSE: #######PowerScale script starting - Test mode value is False#######
VERBOSE: Getting a list of machine from citrix.lab.local based on prefix - VDA
VERBOSE: There are 2 scaled on machines, these will be shutdown as soon as they are empty of users in business hours.
VERBOSE: Performance scaling is enabled - attempting performance metrics capture
VERBOSE: The authentication account provided is in the correct format, continuing
VERBOSE: Starting performance measurement job for VDA02.lab.local using specified credentials
VERBOSE: CIM Connection test for VDA02.lab.local successful
VERBOSE: ThreadID: Beginning 18456
**VERBOSE: Starting performance measurement job for VDA03.lab.local using specified credentials
VERBOSE: CIM Connection test for VDA03.lab.local successful**
VERBOSE: ThreadID: Beginning 18456
VERBOSE: 1 - Overall CPU Average
VERBOSE: 44.5 - Overall Memory Average
VERBOSE: **3000 - Overall Session Index Average**
VERBOSE: 1.5 - Overall Session Count Average
VERBOSE: Start Circular Log Management
VERBOSE: The current number of powered on machines is 2 and the target is 1 - resulting action is to Shutdown 1
machines
VERBOSE: It is currently inside working hours - performing machine analysis
VERBOSE: User logoff mode is not set to force, waiting for sessions to gracefully disconnect before powering machines
down
VERBOSE: No active session found on VDA03.lab.local, performing shutdown
VERBOSE: Machine action for lab\VDA03 - Shutdown immediately

_Originally posted by @alexis-roger in https://github.com/leeej84/PowerScale/issues/27#issuecomment-768950549_

**Comment by leeej84** [comment]
@alexis-roger - Please can you comment here.

**Comment by leeej84** [comment]
I have changed the script behaviour. Machines in maintenance mode will now be counted in working hours to be shutdown and they will be performance managed.

Please retest this exact scenario.

**Comment by alexis-roger** [comment]
Thanks Leee, I just tested and VDA03 is now evaluated for performance metrics, but it is not shutdown:

VERBOSE: -
VERBOSE: #######PowerScale script starting - Test mode value is False#######
VERBOSE: Getting a list of machine from citrix.lab.local based on prefix - VDA
VERBOSE: There are 1 scaled on machines, these will be shutdown as soon as they are empty of users in business hours.
VERBOSE: Performance scaling is enabled - attempting performance metrics capture
VERBOSE: The authentication account provided is in the correct format, continuing
VERBOSE: Starting performance measurement job for VDA02.lab.local using specified credentials
VERBOSE: CIM Connection test for VDA02.lab.local successful
VERBOSE: ThreadID: Beginning 18456
VERBOSE: Starting performance measurement job for VDA03.lab.local using specified credentials
VERBOSE: CIM Connection test for VDA03.lab.local successful
VERBOSE: ThreadID: Beginning 18456
VERBOSE: 1 - Overall CPU Average
VERBOSE: 46.5 - Overall Memory Average
VERBOSE: 3000 - Overall Session Index Average
VERBOSE: 1.5 - Overall Session Count Average
VERBOSE: Start Circular Log Management
VERBOSE: The current number of powered on machines is 1 and the target is 1 - resulting action is to perform Scaling
calculations
VERBOSE: It is currently inside working hours - performing machine analysis
VERBOSE: Additional scaling is not enabled, the number of machines to scale at each run will be set to the default of 1
VERBOSE: The current running machines matches the target machines number, performing scaling analysis
VERBOSE: Scaling has been selected, the current scaling metric is Index and there are 1 machines currently powered off
and there are 1 in maintenance mode available.
VERBOSE: Working with maintenanceMachines this round - maintenance machines will always be selected first
VERBOSE: Machine selected to be placed into service is VDA03.lab.local the machine is powered On and maintename mode is
 True

**Comment by leeej84** [comment]
Okay, you’ve found a cool bug that will only happen within a given scenario.

Ping me over your config file and the latest logfile please.

Kind Regards

Leee Jeffries
Managing Director
Leee Jeffries Consulting

**Comment by alexis-roger** [comment]
[config-logs.zip](https://github.com/leeej84/PowerScale/files/5893342/config-logs.zip)

Here are the files. Thanks Leee.

**Comment by leeej84** [comment]
Hi Alexis

I’ve made some changes to the code. The in hours scale back was using an incorrect value for the current machines, which meant there was effectively nothing to turn off.

I think I’ve cracked it, but…. Please don’t run this in a live environment.

I’ve added some additional logging to allow the extraction of machine states etc... There is a new config creator with a debugLog option. You won't need to use this unless you have an issue.

Kind Regards

Leee Jeffries
Managing Director
Leee Jeffries Consulting

**Comment by leeej84** [comment]
Hi Alexis

I was able to validate your issue with the machine in maintenance mode not be selected.

There is a function in the script that forces the user logoffs. This function look at machines that are On and NOT in maintenance mode. This means that during that evaluation maintenance mode machines would not be looked at until the next script run.

I have amended this so that if the number of maintenance mode machines is greater than 0 the function will work on these machines first. However, the next script run will then shutdown machines with users logged on leaving the server with the larger number of users till last.

I hope this makes sense. If you can re-test all you’ve currently worked with in your test environment and let me know how you get on that would be great.

Kind Regards

Leee Jeffries
Managing Director
Leee Jeffries Consulting

**Comment by leeej84** [comment]
Hi Alexis

Please take the latest scripts from Github today.

I’ve made additional tweaks and fixes to the code.

Kind Regards

Leee Jeffries
Managing Director
Leee Jeffries Consulting

**Comment by alexis-roger** [comment]
Hi Leee,

I still have the same issue with the latest code. here are the logs.
[tb_logs.zip](https://github.com/leeej84/PowerScale/files/5919828/tb_logs.zip)

In my last run I have VDA01 and VDA03 with maintenance mode ON and with 0 sessions but machines are not shutting down.

I'm doing a simple test by connecting up to 12 sessions to 3 servers (VDA01,VDA02,VDA03) and then disconnecting the session and running the script at various stages.

**Comment by leeej84** [comment]
Hallelujah! I can replicate what you see here in my lab.

Now. I will fix it.

Kind Regards

Leee Jeffries
Managing Director
Leee Jeffries Consulting

**Comment by leeej84** [comment]
I have just committed the code to fix this. Thanks very much for all your patience in this. Its greatly appreciated.

Kind Regards

Leee Jeffries
Managing Director
Leee Jeffries Consulting

**Comment by alexis-roger** [comment]
Thanks a lot for your patience and reactivity Leee! Works like a charm :)

**Comment by leeej84** [comment]
Perfect. No problems.

I am planning on adding a feature so you can configure how long a scaled machine to stay on for before it is counted to be shutdown.

Kind Regards

Leee Jeffries
Managing Director
Leee Jeffries Consulting

**Comment by leeej84** [comment]
Confirmed as fixed.
