### ISSUE TITLE
Possible changes and bugs

### ISSUE THREAD

**Issue by jvondermans** [leeej84/PowerScale#3]
Hi Leee,

Your script is very helpfull for while implementing Citrix on Azure. I do have a few suggestions you might want to take up in next releases.

I have been struggeling why the machines didn't start in time. you have to alter -le in -lt and -gt in -ge to make it work

`Function TimeCheck($timeObj) 
{
    If (($timesObj.timeNow.Hour -le $timesObj.startTime.Hour) -or ($timesObj.timeNow.Hour -ge $timesObj.endTime.Hour)) 
{
        Return "OutOfHours" #OutOfHours as we are outside of working hours
    } ElseIf (($timesObj.timeNow.Hour -gt $timesObj.startTime.Hour) -and ($timesObj.timeNow.Hour -lt $timesObj.endTime.Hour)) {
        Return "InsideOfHours" #Dont OutOfHours as we are inside working hours
    } Else {
        Return "Error" #Dont do anything if the time calculation is not conclusive
    }
}
`

What I have done as well is in stead of leaving the machine running in the Function LogoffShutdown, is setting them in Maintenancemode. this way you have the possibility to drain your environment when decreasing the number of machines.

Also I have set the sorting of the machines before selecting the top x, this way you sort all machines in stead of sorting the top x. in the comments what I have set using exisiting functions.

`Function LogoffShutdown () {
    [CmdletBinding()]

    param(
    [Parameter(Mandatory=$true, HelpMessage = "Number of machines to power off")]
    [ValidateNotNullOrEmpty()]
    [int]$numberMachines

    )

    WriteLog -Message "User logoff mode is not set to force, waiting for sessions to gracefully disconnect before powering machines down" -Level Info
    $machinesToPowerOff = $machinesOnAndNotMaintenance | Sort-Object -Property SessionCount | Select-Object -First $($numberMachines) #Jordy, To make sure the sorting takes place before the selecting. And ascending in stead of descending
    foreach ($machine in $machinesToPowerOff) {
        #Check for active sessions on each machine before shutting down
        $sessions = $(brokerUserSessions -machineName $($machine.MachineName) | Where-Object {$_.SessionState -eq "Active"} | Select-Object *)
        If ($null -eq $sessions) {
            WriteLog -Message "No active session found on $($machine.DNSName), performing shutdown" -Level Info
            #Shutdown the machines as there are no active sessions (this will include disconnected sessions)
            If (!$testingOnly) { brokerAction -machineName $($machine.MachineName) -machineAction Shutdown }
        } else {
            WriteLog -Message "Active session(s) found on $($machine.DNSName), this machine cannot be gracefully shutdown yet, but will be placed in maintenance mode" -Level Info
            maintenance -machine $machine.MachineName -maintenanceMode On #Jordy, for Draining!
            foreach ($session in $sessions) {
                WriteLog -Message "Sessions active on $($machine.DNSName), $($session.BrokeringUsername) - session length and state $($(New-TimeSpan -Start $($session.EstablishmentTime)).Minutes) Minutes - State $($session.SessionState) " -Level Info
            }
        }
    }
}
`

**Comment by leeej84** [comment]
Thanks for the feedback here, I will implement the changes for you and review.

**Comment by leeej84** [comment]
Nice work Jordy, Thank you; all implemented.
