### ISSUE TITLE
Current master contains diff code

### ISSUE THREAD

**Issue by Pistoletjes** [leeej84/PowerScale#35]
Hi, the current Decision Making.ps1 contains diff information that shouldn't be there. For instance on line 1171:

```
<<<<<<< HEAD
    $machinesToPowerOff = $machinesOnAndNotMaintenance | Sort-Object -Property SessionCount | Select-Object -First $($numberMachines)
=======
```

I guess this should not be in the master branche? Can you please provide the correct ps1?

**Comment by leeej84** [comment]
Done.
